from __future__ import annotations

import base64
import os
from pathlib import Path
from client.core.config import SCREENSHOT_ENCRYPTION_KEY

from cryptography.hazmat.primitives.ciphers.aead import AESGCM


KEY_DIR  = Path("storage") / "keys"
KEY_FILE = KEY_DIR / "device.key"

AES_KEY_LENGTH = 32
NONCE_LENGTH   = 12


def _load_or_create_key() -> bytes:
    """Load encryption key.

    Production safety rule:
    - If SCREENSHOT_ENCRYPTION_KEY is NOT set, we normally FAIL FAST to
      prevent silent undecryptable screenshot data after reinstalls/wipes.

    Escape hatch for local/dev:
    - Set ALLOW_AUTOGENERATED_ENCRYPTION_KEY=true to keep the old fallback
      behavior (generate a new key if missing).
    """
    env_key = SCREENSHOT_ENCRYPTION_KEY

    # If env key is set, that is the source of truth.
    if env_key:
        key = base64.b64decode(env_key)
        if len(key) != AES_KEY_LENGTH:
            raise RuntimeError(
                f"Encryption key must be {AES_KEY_LENGTH} bytes"
            )
        return key

    allow_autogen = os.getenv(
        "ALLOW_AUTOGENERATED_ENCRYPTION_KEY",
        "false",
    ).strip().lower() == "true"

    KEY_DIR.mkdir(parents=True, exist_ok=True)

    if KEY_FILE.exists():
        raw = KEY_FILE.read_bytes()
        if len(raw) == AES_KEY_LENGTH:
            return raw
        # Corrupt/wrong-length key file — this WILL orphan any existing
        # .enc files encrypted with the old key.
        if not allow_autogen:
            raise RuntimeError(
                "Existing storage/keys/device.key has invalid length; "
                "refusing to auto-generate a new key in production. "
                "Set ALLOW_AUTOGENERATED_ENCRYPTION_KEY=true to allow fallback."
            )
        _warn_new_key(
            "storage/keys/device.key existing key file is invalid length"
        )
        KEY_FILE.unlink()
    else:
        if not allow_autogen:
            raise RuntimeError(
                "SCREENSHOT_ENCRYPTION_KEY environment variable is not set. "
                "Set it in .env before running in production — without it, "
                "screenshots cannot be reliably decrypted across reinstalls."
            )
        _warn_new_key(
            "SCREENSHOT_ENCRYPTION_KEY not set in .env and no device.key found"
        )

    # Fallback path (dev/local only): generate a new local key.
    key = os.urandom(AES_KEY_LENGTH)
    KEY_FILE.write_bytes(key)
    return key



def _warn_new_key(reason: str) -> None:
    """Generating a brand-new local key — log it so it's not silent."""
    try:
        # Local import to avoid circular import at module load time.
        from client.services.logger_service import LoggerService
        LoggerService.log(
            f"CryptoEngine: generating NEW local encryption key ({reason}). "
            f"Any screenshots encrypted with a previous key on this machine "
            f"will no longer be decryptable."
        )
    except Exception:
        pass


def _get_aesgcm() -> AESGCM:
    return AESGCM(_load_or_create_key())


class CryptoEngine:

    @staticmethod
    def encrypt_bytes(plaintext: bytes) -> bytes:
        aesgcm = _get_aesgcm()
        nonce  = os.urandom(NONCE_LENGTH)
        ct     = aesgcm.encrypt(nonce, plaintext, None)
        return nonce + ct

    @staticmethod
    def decrypt_bytes(blob: bytes) -> bytes:
        if len(blob) <= NONCE_LENGTH:
            raise ValueError(f"Blob too short: {len(blob)} bytes")
        nonce = blob[:NONCE_LENGTH]
        ct    = blob[NONCE_LENGTH:]
        try:
            return _get_aesgcm().decrypt(nonce, ct, None)
        except Exception as exc:
            raise ValueError(f"AES-GCM decryption failed: {exc}") from exc

    @staticmethod
    def save_encrypted(plaintext: bytes, dest_path: str | Path) -> Path:
        dest = Path(dest_path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(CryptoEngine.encrypt_bytes(plaintext))
        return dest

    @staticmethod
    def load_decrypted(src_path: str | Path) -> bytes:
        return CryptoEngine.decrypt_bytes(Path(src_path).read_bytes())

    @staticmethod
    def encrypt_file(plain_path: str | Path) -> Path:
        plain_path = Path(plain_path)
        enc_path   = plain_path.with_suffix(".bin")
        CryptoEngine.save_encrypted(plain_path.read_bytes(), enc_path)
        plain_path.unlink(missing_ok=True)
        return enc_path

    @staticmethod
    def encrypt_token(plaintext_token: str) -> str:
        blob = CryptoEngine.encrypt_bytes(plaintext_token.encode("utf-8"))
        return base64.b64encode(blob).decode("ascii")

    @staticmethod
    def decrypt_token(encrypted_b64: str) -> str:
        blob = base64.b64decode(encrypted_b64.encode("ascii"))
        return CryptoEngine.decrypt_bytes(blob).decode("utf-8")
